### ISSUE TITLE
Pos（位指示宏）和Msk（位屏蔽宏）的使用

### ISSUE THREAD

**Issue by Henderson-H** [laterTonight/laterTonight.GitHub.io#3]
```
#define BASETIM_CR_TMR_PRSC_Pos               (0UL)                     /*!< BASETIM CR: TMR_PRSC (Bit 0)                              */
#define BASETIM_CR_TMR_PRSC_Msk               (0x7UL)                   /*!< BASETIM CR: TMR_PRSC (Bitfield-Mask: 0x07)                */
```
其中的寄存器位指示宏：xxx_Pos ，宏展开后即为 xxx 在相应寄存器中的位置，如控制 Base Timer 时钟源的 BASETIM_CR_TMR_PRSC_Pos，宏展开为 0UL，这个寄存器位正是在寄存器 TIMx_CR 中的 Bit0。

而寄存器位屏蔽宏：xxx_Msk，宏展开是 xxx 的位全部置 1 后，左移 SysTick_xxx_Pos 位。如控制 Base Timer 时钟源的BASETIM_CR_TMR_PRSC_Msk，宏展开为  (7UL<< BASETIM_CR_TMR_PRSC_Pos )  ，把无符号长整型数值(UL) 1 左移 0 位，得到了一个只有 TMR_PRSC[2:0] 被置 1，其它位为 0 的数值，这样的数值配合位操作  &(按位与)、| (按位或)可以很方便地修改寄存器的某些位。假如控制 TMR_PRSC( TIM预除频选择) 需要3个寄存器位，这个宏就应该被改为(0xFUL << BASETIM_CR_TMR_PRSC_Pos )  ，这样就会得到一个关于 TMR_PRSC( TIM预除频选择) 的3位被置 1 的值，这些宏的参数就是这样被确定的。

**Comment by 0xuchao0** [comment]
谢谢佬解惑
